version = 0.1

[default.deploy.parameters]
stack_name = "medclear-prod"
resolve_s3 = true
s3_prefix = "medclear-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true

